sudo: false

language: java

install: true

before_script:
  - _JAVA_OPTIONS=

script:
- ant build
- ant test

jdk:
  - openjdk7

after_script:
- curl --ftp-create-dirs
       -T tests/all_results.zip
       ${CURL_URL_BASE}/build/all_results_b_6_0.zip
