apiVersion: v1
kind: Service

metadata:
  name: jppf-driver-service

spec:
  ports:
  - port: 11111
    targetPort: jppf
    protocol: TCP
    name: jppf1
  - port: 11443
    targetPort: jppf-tls
    protocol: TCP
    name: jppf2

  selector:
    app.kubernetes.io/name: {{ include "jppf.name" . }}-driver
    app.kubernetes.io/instance: {{ .Release.Name }}-driver

  type: NodePort
