apiVersion: v1
kind: Service

metadata:
  name: jppf-driver-service

spec:
  ports:
  - port: 11111
    nodePort: {{ .Values.driver.servicePort }}
    targetPort: jppf
    protocol: TCP
    name: jppf1
  - port: 11443
    nodePort: {{ .Values.driver.servicePortTLS }}
    targetPort: jppf-tls
    protocol: TCP
    name: jppf2

  selector:
    driver.name: {{ .Values.driver.name }}

  type: NodePort
