version: "3"

services:
  jppf-driver:
    image: "jppfgrid/jppf-driver:${JPPF_VERSION}"
    env_file:
    - .env
    ports:
      - "11111:11111"
      - "11443:11443"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s
      placement:
        constraints:
          # force the driver to be deployed on the docker swarm node that starts the service stack
          # i.e. where the 'docker stack deploy ...' command is issued
          - node.labels.jppf_server_host == ${JPPF_SERVER_HOST}
    networks:
      jppfnet:

  jppf-node:
    image: "jppfgrid/jppf-node:${JPPF_VERSION}"
    env_file:
    - .env
    environment:
    - JPPF_SERVER_HOST
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s
    networks:
      jppfnet:

networks:
  jppfnet:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: "${JPPF_SUBNET}"
