# This is an example yaml file which overrrides values in the JPPF chart

# driver-specific configuration values
driver:
  # options of the driver JVM
  jvmOptions: "-Xmx256m -Xms64m"
  servicePort: 31111
  servicePortTLS: 31443
  # CPU and memory allocation to the driver
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"
  configOverrides: |-
    custom.driver.prop = driver value

# node-specific configuration values
node:
  # number of nodes in the JPPF grid
  replicas: 2
  # options of the node JVM
  jvmOptions: "-Xmx128m -Xms32m"
  # number of threads processing tasks
  processingThreads: "1"
  # maximum number of jobs a node can handle concurrently
  maxConcurrentJobs: "10"
  # CPU and memory allocation to each node
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  configOverrides: |-
    custom.node.prop = node value

# admin console specific configuration values
admin:
  # whether to deploy the console or not
  enabled: true
  servicePort: 31180
  # base64-encoded content of a tomcat-users.xml file
  tomcatUsers: "PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0ndXRmLTgnPz4KPHRvbWNhdC11c2Vycz4KICA8cm9sZSByb2xlbmFtZT0ianBwZi1hZG1pbiIvPgogIDxyb2xlIHJvbGVuYW1lPSJqcHBmLW1hbmFnZXIiLz4KICA8cm9sZSByb2xlbmFtZT0ianBwZi1tb25pdG9yIi8+CiAgPHVzZXIgdXNlcm5hbWU9ImpwcGYiIHBhc3N3b3JkPSJqcHBmIiByb2xlcz0ianBwZi1tYW5hZ2VyLGpwcGYtYWRtaW4iLz4KICA8dXNlciB1c2VybmFtZT0ianBwZjIiIHBhc3N3b3JkPSJqcHBmMiIgcm9sZXM9ImpwcGYtbWFuYWdlcixqcHBmLWFkbWluIi8+CiAgPHVzZXIgdXNlcm5hbWU9ImFkbWluIiBwYXNzd29yZD0iYWRtaW4iIHJvbGVzPSJqcHBmLWFkbWluIi8+CiAgPHVzZXIgdXNlcm5hbWU9Im1hbmFnZXIiIHBhc3N3b3JkPSJtYW5hZ2VyIiByb2xlcz0ianBwZi1tYW5hZ2VyIi8+CiAgPHVzZXIgdXNlcm5hbWU9Im1vbml0b3IiIHBhc3N3b3JkPSJtb25pdG9yIiByb2xlcz0ianBwZi1tb25pdG9yIi8+CjwvdG9tY2F0LXVzZXJzPgo="
  # CPU and memory allocation to the web console
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  configOverrides: |-
    custom.admin.prop = admin value

# values common to driver and nodes
jppf:
  # 10.244.0.0/16 for flannel CNI plugin
  subnet: "10.244.0.0/16"
  version: "6.2-beta"

tls:
  # whether secure TLS communication is enabled
  enabled: false
