version: "3"

services:

  # the JPPF driver
  jppf-driver:
    image: "jppfgrid/jppf-driver:${JPPF_VERSION}"

    env_file:
    - .env

    ports:
      # plain port
      - "11111:11111"
      # TLS port
      - "11443:11443"

    volumes:
    # Mount the TLS truststores, keystore and associated passwords
    # Uncomment these lines when JPPF_TLS_ENABLED=true, and change the source paths as needed
    #- ./tls/driver_keystore.ks:/jppf-config/driver_keystore.ks
    #- ./tls/driver_keystore.txt:/jppf-config/driver_keystore.txt
    #- ./tls/client_truststore.ks:/jppf-config/client_truststore.ks
    #- ./tls/client_truststore.txt:/jppf-config/client_truststore.txt
    #- ./tls/node_truststore.ks:/jppf-config/node_truststore.ks
    #- ./tls/node_truststore.txt:/jppf-config/node_truststore.txt
    # Uncomment this line to mount additional JPPF configuration properties, changing the source path as needed
    #- ./config-overrides/driver-overrides.properties:/jppf-config-overrides/config-overrides.properties

    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s
    networks:
      jppfnet:

  # the JPPF nodes
  jppf-node:
    image: "jppfgrid/jppf-node:${JPPF_VERSION}"

    env_file:
    - .env

    volumes:
    # Mount the TLS truststore, keystore and associated passwords
    # Uncomment these lines when JPPF_TLS_ENABLED=true, and change the source paths as needed
    #- ./tls/node_keystore.ks:/jppf-config/node_keystore.ks
    #- ./tls/node_keystore.txt:/jppf-config/node_keystore.txt
    #- ./tls/driver_truststore.ks:/jppf-config/driver_truststore.ks
    #- ./tls/driver_truststore.txt:/jppf-config/driver_truststore.txt
    # Uncomment this line to mount additional JPPF configuration properties, changing the source path as needed
    #- ./config-overrides/node-overrides.properties:/jppf-config-overrides/config-overrides.properties

    deploy:
      replicas: ${JPPF_NB_NODES}
      resources:
        limits:
          cpus: "1"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s
    networks:
      jppfnet:

  # the JPPF web administration console
  jppf-admin-web:
    image: "jppfgrid/jppf-admin-web:${JPPF_VERSION}"

    env_file:
    - .env

    volumes:
    # Mount the Tomcat user registry
    - ./tomcat-users.xml:/tomcat-conf/tomcat-users.xml

    # Mount the TLS truststore, keystore and associated passwords
    # Uncomment these lines when JPPF_TLS_ENABLED=true, and change the source paths as needed
    #- ./tls/client_keystore.ks:/jppf-config/client_keystore.ks
    #- ./tls/client_keystore.txt:/jppf-config/client_keystore.txt
    #- ./tls/driver_truststore.ks:/jppf-config/driver_truststore.ks
    #- ./tls/driver_truststore.txt:/jppf-config/driver_truststore.txt

    # Uncomment this line to mount additional JPPF configuration properties, changing the source path as needed
    #- ./config-overrides/admin-overrides.properties:/jppf-config-overrides/config-overrides.properties

    ports:
      - "8080:8080"

    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s
    networks:
      jppfnet:

networks:
  jppfnet:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: "${JPPF_SUBNET}"
