version: "3"

services:

  # the JPPF driver
  jppf-driver:
    image: "jppfgrid/jppf-driver:${JPPF_VERSION}"
    env_file:
    - .env
    ports:
      # plain port
      - "11111:11111"
      # TLS port
      - "11443:11443"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s
    networks:
      jppfnet:

  # the JPPF nodes
  jppf-node:
    image: "jppfgrid/jppf-node:${JPPF_VERSION}"
    env_file:
    - .env
    environment:
    - JPPF_SERVER_HOST
    deploy:
      replicas: ${JPPF_NB_NODES}
      resources:
        limits:
          cpus: "1"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s
    networks:
      jppfnet:

  # the JPPF web administration console
  jppf-admin-web:
    image: "jppfgrid/jppf-admin-web:${JPPF_VERSION}"
    env_file:
    - .env
    environment:
    - JPPF_SERVER_HOST
    volumes:
    - ${JPPF_TOMCAT_USERS_FILE}:/tomcat-conf/tomcat-users.xml
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s
    networks:
      jppfnet:

networks:
  jppfnet:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: "${JPPF_SUBNET}"
