{{- if and .Values.admin.enabled .Values.tls.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: admin-tls-config
type: Opaque
data:
  adminKeyStore: {{ .Values.tls.admin.keystore }}
  adminKeyStorePassword: {{ .Values.tls.admin.keystorePassword }}
  driverTrustStore: {{ .Values.tls.driver.truststore }}
  driverTrustStorePassword: {{ .Values.tls.driver.truststorePassword }}
{{- end }}

