apiVersion: v1
kind: Service

metadata:
  name: jppf-driver-service

spec:
  ports:
  - port: 11443
    {{- if .Values.driver.servicePortTLS }}
      {{- if eq .Values.driver.serviceType "NodePort" }}
    nodePort: {{ .Values.driver.servicePortTLS }}
      {{- end }}
    {{- end }}
    targetPort: jppf-tls
    protocol: TCP
    name: jppf2
  - port: 11111
    {{- if .Values.admin.servicePort }}
      {{- if eq .Values.driver.serviceType "NodePort" }}
    nodePort: {{ .Values.driver.servicePort }}
      {{- end }}
    {{- end }}
    targetPort: jppf
    protocol: TCP
    name: jppf1

  selector:
    app: jppf
    comp: driver
    release: "{{ .Release.Name }}"

  {{ if eq .Values.driver.serviceType "NodePort" }}
  type: NodePort
  {{ else }}
  type: ClusterIP
  {{ end }}
