{{- if .Values.tls.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: driver-tls-config
type: Opaque
data:
  driverKeyStore: {{ .Values.tls.driver.keystore }}
  driverKeyStorePassword: {{ .Values.tls.driver.keystorePassword }}
  clientTrustStore: {{ .Values.tls.admin.truststore }}
  clientTrustStorePassword: {{ .Values.tls.admin.truststorePassword }}
  nodeTrustStore: {{ .Values.tls.node.truststore }}
  nodeTrustStorePassword: {{ .Values.tls.node.truststorePassword }}
{{- end }}

