{{- if .Values.tls.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: node-tls-config
type: Opaque
data:
  nodeKeyStore: {{ .Values.tls.node.keystore }}
  nodeKeyStorePassword: {{ .Values.tls.node.keystorePassword }}
  driverTrustStore: {{ .Values.tls.driver.truststore }}
  driverTrustStorePassword: {{ .Values.tls.driver.truststorePassword }}
{{- end }}

